# DataSource settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_hexagonal_architecture?useSSL=false&serverTimezone=America/Lima
    username: root
    password: magadiflo
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

# Logging settings
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
